export default {
  created_at: 'Sat May 01 02:58:35 +0000 2021',
  id: 1388326957109022700,
  id_str: '1388326957109022724',
  text: 'Gif and Text https://t.co/xHe7DqTf69',
  display_text_range: [0, 12],
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 3512096904,
    id_str: '3512096904',
    name: 'DBKynd',
    screen_name: 'DBK_Test',
    location: null,
    url: null,
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 0,
    friends_count: 0,
    listed_count: 0,
    favourites_count: 0,
    statuses_count: 529,
    created_at: 'Thu Sep 10 05:33:59 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url:
      'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_image_url_https:
      'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [],
    symbols: [],
    media: [
      {
        id: 1388326947042730000,
        id_str: '1388326947042729984',
        indices: [13, 36],
        description: 'Proud Of You Yes GIF',
        media_url: 'http://pbs.twimg.com/tweet_video_thumb/E0RUAK6VoAA-_s5.jpg',
        media_url_https:
          'https://pbs.twimg.com/tweet_video_thumb/E0RUAK6VoAA-_s5.jpg',
        url: 'https://t.co/xHe7DqTf69',
        display_url: 'pic.twitter.com/xHe7DqTf69',
        expanded_url:
          'https://twitter.com/DBK_Test/status/1388326957109022724/photo/1',
        type: 'photo',
        sizes: {
          thumb: {
            w: 150,
            h: 150,
            resize: 'crop',
          },
          medium: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
          small: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
          large: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
        },
      },
    ],
  },
  extended_entities: {
    media: [
      {
        id: 1388326947042730000,
        id_str: '1388326947042729984',
        indices: [13, 36],
        description: 'Proud Of You Yes GIF',
        media_url: 'http://pbs.twimg.com/tweet_video_thumb/E0RUAK6VoAA-_s5.jpg',
        media_url_https:
          'https://pbs.twimg.com/tweet_video_thumb/E0RUAK6VoAA-_s5.jpg',
        url: 'https://t.co/xHe7DqTf69',
        display_url: 'pic.twitter.com/xHe7DqTf69',
        expanded_url:
          'https://twitter.com/DBK_Test/status/1388326957109022724/photo/1',
        type: 'animated_gif',
        video_info: {
          aspect_ratio: [61, 64],
          variants: [
            {
              bitrate: 0,
              content_type: 'video/mp4',
              url: 'https://video.twimg.com/tweet_video/E0RUAK6VoAA-_s5.mp4',
            },
          ],
        },
        sizes: {
          thumb: {
            w: 150,
            h: 150,
            resize: 'crop',
          },
          medium: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
          small: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
          large: {
            w: 244,
            h: 256,
            resize: 'fit',
          },
        },
      },
    ],
  },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1619837915099',
}
