export default {
  created_at: 'Sat May 01 02:36:27 +0000 2021',
  id: 1388321389526982700,
  id_str: '1388321389526982656',
  text: 'text only',
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 3512096904,
    id_str: '3512096904',
    name: 'DBKynd',
    screen_name: 'DBK_Test',
    location: null,
    url: null,
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 0,
    friends_count: 0,
    listed_count: 0,
    favourites_count: 0,
    statuses_count: 519,
    created_at: 'Thu Sep 10 05:33:59 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url:
      'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_image_url_https:
      'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [],
    symbols: [],
  },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1619836587684',
}
