export default {
  created_at: 'Sat May 01 03:14:27 +0000 2021',
  id: 1388330951067930600,
  id_str: '1388330951067930631',
  text:
    'A really really long text that is over 140 characters that will be in extended entities so that we can test what ha… https://t.co/ePEXSnds3G',
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  truncated: true,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 3512096904,
    id_str: '3512096904',
    name: 'DBKynd',
    screen_name: 'DBK_Test',
    location: null,
    url: null,
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 0,
    friends_count: 0,
    listed_count: 0,
    favourites_count: 0,
    statuses_count: 534,
    created_at: 'Thu Sep 10 05:33:59 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url:
      'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_image_url_https:
      'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: [],
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  extended_tweet: {
    full_text:
      'A really really long text that is over 140 characters that will be in extended entities so that we can test what happens with extended entities. https://t.co/CjHOWjB1jP\nhttps://t.co/LLa0TshkEu',
    display_text_range: [0, 192],
    entities: {
      hashtags: [],
      urls: [
        {
          url: 'https://t.co/CjHOWjB1jP',
          expanded_url: 'https://wordcounter.net/character-count',
          display_url: 'wordcounter.net/character-count',
          indices: [145, 168],
        },
        {
          url: 'https://t.co/LLa0TshkEu',
          expanded_url: 'https://google.com',
          display_url: 'google.com',
          indices: [169, 192],
        },
      ],
      user_mentions: [],
      symbols: [],
    },
  },
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [
      {
        url: 'https://t.co/ePEXSnds3G',
        expanded_url: 'https://twitter.com/i/web/status/1388330951067930631',
        display_url: 'twitter.com/i/web/status/1…',
        indices: [117, 140],
      },
    ],
    user_mentions: [],
    symbols: [],
  },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1619838867333',
}
